# List of tox files to ignore
# example: tests/framework_django/tox-0110.ini
disable:
    - tests/adapter_gevent/tox.ini
    - tests/datastore_motor/tox.ini
    - tests/datastore_pymssql/tox.ini
    - tests/external_awscli/tox.ini
